In [79]:
# %pip install pandas numpy matplotlib seaborn scikit-learn pyarrow Jinja2

In [80]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [81]:
import os
from IPython.display import display


data_folder = './data_for_test_arch/'

ana_sales_df = pd.read_parquet(os.path.join(data_folder, 'ana_sales_data.parquet'))
ana_upc_df = pd.read_parquet(os.path.join(data_folder, 'ana_upc.parquet'))
beer_sales_df = pd.read_parquet(os.path.join(data_folder, 'beer_sales_data.parquet'))
beer_upc_df = pd.read_parquet(os.path.join(data_folder, 'beer_upc.parquet'))
cig_sales_df = pd.read_parquet(os.path.join(data_folder, 'cig_sales_data.parquet'))
cig_upc_df = pd.read_parquet(os.path.join(data_folder, 'cig_upc.parquet'))
demographics_df = pd.read_parquet(os.path.join(data_folder, 'demographic_data.parquet'))


## Отображаем основные данные о таблицах 

---

In [107]:
display(ana_sales_df.info(), 
        ana_sales_df.head().style.set_caption('ana_sales head')
        )
 
display(ana_upc_df.info(), 
        ana_upc_df.head().style.set_caption('ana_upc head')
        )

<class 'pandas.core.frame.DataFrame'>
Index: 7241655 entries, 0 to 7339216
Data columns (total 7 columns):
 #   Column  Dtype  
---  ------  -----  
 0   store   float64
 1   upc     float64
 2   week    float64
 3   move    float64
 4   qty     float64
 5   price   float64
 6   sale    object 
dtypes: float64(6), object(1)
memory usage: 442.0+ MB


None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641 entries, 0 to 640
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   com_code  641 non-null    int64 
 1   upc       641 non-null    int64 
 2   descrip   641 non-null    object
 3   size      641 non-null    object
 4   case      641 non-null    int64 
 5   nitem     641 non-null    int64 
dtypes: int64(4), object(2)
memory usage: 30.2+ KB


None

---

In [83]:

display(beer_sales_df.head().style.set_caption('beer_sales head'), 
        beer_upc_df.head().style.set_caption('beer_upc head'))
display(beer_upc_df.info(), beer_sales_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   com_code  790 non-null    int64 
 1   upc       790 non-null    int64 
 2   descrip   790 non-null    object
 3   size      790 non-null    object
 4   case      790 non-null    int64 
 5   nitem     790 non-null    int64 
dtypes: int64(4), object(2)
memory usage: 37.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 3967720 entries, 0 to 3990671
Data columns (total 7 columns):
 #   Column  Dtype  
---  ------  -----  
 0   store   int64  
 1   upc     int64  
 2   week    int64  
 3   move    int64  
 4   qty     int64  
 5   price   float64
 6   sale    object 
dtypes: float64(1), int64(5), object(1)
memory usage: 242.2+ MB


None

None

---

In [84]:

display(cig_sales_df.head().style.set_caption('cig_sales head'), 
        cig_upc_df.head().style.set_caption('cig_upc head'))
display(cig_upc_df.info(), cig_sales_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   com_code  942 non-null    int64 
 1   upc       942 non-null    int64 
 2   descrip   942 non-null    object
 3   size      942 non-null    object
 4   case      942 non-null    int64 
 5   nitem     942 non-null    int64 
dtypes: int64(4), object(2)
memory usage: 44.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 5331369 entries, 0 to 5398196
Data columns (total 7 columns):
 #   Column  Dtype  
---  ------  -----  
 0   store   int64  
 1   upc     int64  
 2   week    int64  
 3   move    int64  
 4   qty     int64  
 5   price   float64
 6   sale    object 
dtypes: float64(1), int64(5), object(1)
memory usage: 325.4+ MB


None

None

---

In [85]:

display(demographics_df.head().style.set_caption('demographics head'))
display(demographics_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 107 entries, 1 to 107
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   store     107 non-null    float64
 1   age60     97 non-null     float32
 2   age9      97 non-null     float32
 3   educ      97 non-null     float32
 4   ethnic    97 non-null     float32
 5   income    97 non-null     float32
 6   hhlarge   97 non-null     float32
 7   workwom   97 non-null     float32
 8   hval150   97 non-null     float32
 9   sstrdist  85 non-null     float32
 10  sstrvol   85 non-null     float32
 11  cpdist5   85 non-null     float32
 12  cpwvol5   85 non-null     float32
dtypes: float32(12), float64(1)
memory usage: 6.7 KB


None

In [ ]:
# Мусорные данные
ana_upc_df['com_code']


array([953])

In [ ]:
ana_sales_df

ana_sales_df.isna().sum()
ana_sales_df['sale'].notna().sum()



store    9153
upc      9153
week     9153
move     9153
qty      9153
price    9153
sale        1
dtype: int64

In [108]:
ana_sales_df['price'].min(), ana_sales_df['price'].max()
ana_sales_df['price'].mean(), ana_sales_df['price'].median()

non_price_rows = ana_sales_df['price'] == 0
priced_rows = ana_sales_df['price'] > 0

ana_sales_df[non_price_rows] = round(ana_sales_df[priced_rows]['price'].mean())
ana_sales_df[ana_sales_df['price'] > 15].count()


store    9153
upc      9153
week     9153
move     9153
qty      9153
price    9153
sale        1
dtype: int64

In [ ]:
beer_upc_df['com_code'].unique()

array([27, 26, 28])

In [ ]:
cig_upc_df['com_code'].unique()

array([700, 705])

---